### ISSUE TITLE
Plugins problems with linux ( keepass 2.38 ) + pinout misunderstood

### ISSUE THREAD

**Issue by NewRedsquare** [seeers/PW-Stick#10]
Hello and thanks again for providing this github !

I installed Keepass 2.38 with ubuntu repositories ( it uses mono ). I copied the PWstick.dll plugin into the correct path. When i restart KeePass , i have " non compatible plugin ". The thing I don't understand is that it works like a charm on windows with the same keepass version. I installed mono-complete. Any ideas ?

When reading the .ino code , I don't understand where is A5 pin and strange that you can only have 8 buttons ( most strange fact is that they're soldered by two ports and not like casual : to port and to GND )
That's maybe not best explaination ( I'm French :D )

Debian-10

**Comment by NewRedsquare** [comment]
After reading more the code and searched more about arduino, i found solution for buttons.

**Comment by matthgyver** [comment]
Salut,

Désolé de ne pas avoir répondu, je ne reçois pas de notifications sur les issues (faut que je regarde de plus près).

Pour Mono je ne peux pas te répondre, je n'ai pas testé. J'aimerais une solution plus universelle que Keepass car çle plugin ne fonctionne que sous windows mais je n'ai pas les connaissances pour développer quelque chose :-/

Concernant le cablage je n'ai pas bien saisi ce que tu veux dire désolé.
