### ISSUE TITLE
Problem with the plugin on windows

### ISSUE THREAD

**Issue by NewRedsquare** [seeers/PW-Stick#12]
Hello again,
As i'm still trying to get this working, i successfully burned the code into my arduino pro-micro.
I have keepass 2.41 installed on my computer and put the pwkeeper.dll plugin in the plugin/ folder.
I connect it to windows, I type the default password ' 0000 ' and unlocked the key but when trying to change settings of the key or reading its data, i always have ' No key found '.
when i press "0" button on my key, it locks the computer like it should do.
I precise that i already tried on another computer.
Thanks again for this recent update !

Debian-10

**Comment by tinker4545** [comment]
The Plugin is compiled for KeePass 2.32

**Comment by NewRedsquare** [comment]
> The Plugin is compiled for KeePass 2.32

Regarding the wiki , the plugin works on 2.41 too.

**Comment by tinker4545** [comment]
Ah ur right im on the old version, try 2.32 anyways just to see

**Comment by NewRedsquare** [comment]
What is your version of keepass when the plugin work for you ?

**Comment by matthgyver** [comment]
Hi,

It's work with the last version of Keepass (a friend have tested recently).

Have you installed the Arduino IDE on your windows ? It act as a "driver" and it's needed to configure the stick with Keepass. *(only for configure it, you can use it on any computer without IDE)*

What version did you use ? (stik or desktop)

**Comment by NewRedsquare** [comment]
Hello, i have the arduino ide on my computer.
The most strange fact is that i tested the stick month ago and it worked but now not . ( Even with same arduino version and same keepass )

PS : I'm french :+1:

**Comment by NewRedsquare** [comment]
I don't understand at all , i previously reinstalled the arduino ide but i did it now again and it works. But for how many time ?

**Comment by tinker4545** [comment]
> s

2.32   anyways glad u got it working

**Comment by matthgyver** [comment]
Strange. Maybe due to system update.

**Comment by NewRedsquare** [comment]
So now , if I want to connect my key with keepass on another computer, should I install arduino on it ?

**Comment by matthgyver** [comment]
Yes.
Arduino IDE contain a driver that allow serial communication between computer and Arduino. Serial communication is used for push data into Arduino memory so for send logins, passwords and setting to the stick with Keepass.

Maybe driver installation (https://www.arduino.cc/en/Guide/DriverInstallation) is enougth. I have'nt tested.

**Comment by NewRedsquare** [comment]
Thanks a lot for help !
