### ISSUE TITLE
[Question] Bootloader

### ISSUE THREAD

**Issue by matthgyver** [seeers/PW-Stick#3]
Hi,

Does I need to burn the Arduino bootloader ?
I've tested with the default Atmega bootloader and upload scketch with Arduino IDE .
Upload was OK but the stick does'nt work.

I've read lot of things about burning arduino bootloader on Atmega 32u4 and make lot of tests but I can't burn the bootloader.
How have you proceed please ?

Thank you

**Comment by seeers** [comment]
Hi, 

yes you need to burn the Arduino Leonardo Bootloader to the Atmega32u4. 
Just connect the ISP Pins to a USPASP or a similar ISP and burn the Bootloader with the Arduino IDE.

**Comment by matthgyver** [comment]
I take my head with a bad programmer and some other things.
I've converted an arduino as an ISP programmer and this tutorial help me : https://murchlabs.com/monday-experiment-bootloading-an-atmega32u4-with-arduino/
All is ok now ! Work perfectly !
Thank you Seers ;-)
