### ISSUE TITLE
AESLib related IDE error

### ISSUE THREAD

**Issue by tinker4545** [seeers/PW-Stick#6]
Thx seers for your work, i have a problem, im getting error codes relating to AESLib (see below) 
Ive tried arduino 1.0.4 aswell as 1.0.5-r2.
What is the 'HardwarePWManager.v12.suo' ? do i need to do anything with this file?
Many thanks

Documents\Arduino\libraries\AESLib\AESLib.c: In function 'aes128_enc_multiple':
Documents\Arduino\libraries\AESLib\AESLib.c:75: error: 'for' loop initial declaration used outside C99 mode
\Documents\Arduino\libraries\AESLib\AESLib.c: In function 'aes256_enc_multiple':
\Documents\Arduino\libraries\AESLib\AESLib.c:95: error: 'for' loop initial declaration used outside C99 mode
\Documents\Arduino\libraries\AESLib\AESLib.c: In function 'aes128_dec_multiple':
Documents\Arduino\libraries\AESLib\AESLib.c:213: error: 'for' loop initial declaration used outside C99 mode
Documents\Arduino\libraries\AESLib\AESLib.c: In function 'aes256_dec_multiple':
\Documents\Arduino\libraries\AESLib\AESLib.c:233: error: 'for' loop initial declaration used outside C99 mode

matt i moved it over to here, cheers

**Comment by matthgyver** [comment]
Hi,
I've problem with Arduino version > 1.0.5 but it's not the same (error on keyboard.h).
I've not this error but I'm on Linux and the compiler or compilation setting are maybe different.
Try to modifiy de lib file like as described here : https://stackoverflow.com/questions/24881/how-do-i-fix-for-loop-initial-declaration-used-outside-c99-mode-gcc-error
(Extract the i variable declaration from the loop)

For the suo file, google give me the response : https://fileinfo.com/extension/suo

**Comment by tinker4545** [comment]
matt ur a star! i followed the links and finally got it to compile :-) I edited the .h file :-) 1st time doing it lol

another question for you if you dont mind, im putting together seers prototype version using a full pro micro, looking at the schematic i will need other components, can you tell what ones I need? I got the buttons soldered and ready and the WS2812b is in the mail.

**Comment by matthgyver** [comment]
You just need buttons and WS2812b.
Take a look into the "desktop version" folder. I'm using only a full pro micro, switch and LED.
Source code is for the final version so you'll modify it for define PIN correctly I think.
Schematic is for building from scratch.

**Comment by tinker4545** [comment]
ah i see, no wonder i was confused a little, makes sense now. il look at the desktop version later.

thanks again for your help (i was gonna give up this project)

**Comment by matthgyver** [comment]
You'r welcome
