### ISSUE TITLE
UK keyboard layout

### ISSUE THREAD

**Issue by tinker4545** [seeers/PW-Stick#8]
Hi Seers, 
Can you help me out with a small problem, i got everything running but the keyboard layout is US i need a UK layout, ive been trying to change it in the HID.cpp but got all mixed up, is there a way to change it all at once?
Thanks,  great project btw

**Comment by matthgyver** [comment]
Hi Tinker,

Keyboard layout on Arduino is'nt simple :-/ There's no library like the Teensy board have by exemple.

I needed French Azerty layout and don't found anything working great so I build my own : https://github.com/matthgyver/Arduino-Keyboard-FR

Maybe you could build your own. This link helped me : 
* https://raw.githubusercontent.com/qlyoung/armory-keyboard/master/layouts/keyboard-layout.png
* https://www.ascii-code.com/
