### ISSUE TITLE
FAO Matt

### ISSUE THREAD

**Issue by tinker4545** [seeers/PW-Stick#9]
Hi Matt, 

I see Seers put a fix up, just wondering are you going to update your desktop version with the fix? (if it works ;-)

also, In your desktop version I see you have keyboard.h defined, is there anyway I can get the UK keyboard to work?

Thx

**Comment by matthgyver** [comment]
Hi,

I've not the time to update the desktop version. Maybe this week-end.
I think that the UK keyboard will work. The keyboard definition is on HID.cpp file (into the arduino requirement folder)

**Comment by tinker4545** [comment]
Hi Matt,

Thanks, I edited the HID.cpp file, i only managed to get the " and @ to work rite, for the life of me i cant get the other keys to swap over, been at it days now :-( I was hoping there would be an easier way, do you use a US keyboard?

I look forward to the bug being fixed :-)
Thx agin

**Comment by matthgyver** [comment]
Hi,

I'm french and dont well understand your problem, even with google translate :-/
I'm using a french keyboard.

**Comment by tinker4545** [comment]
ok matt no worries, forget about the keyboard. I think the bug is more important for now :-)

**Comment by matthgyver** [comment]
Hi,
Code was updated but I forgot to close this issue.
